Ultimaker/fdm_materials

- ultimaker_abs_black.xml.fdm_material
- ultimaker_abs_blue.xml.fdm_material
- ultimaker_abs_green.xml.fdm_material
- ultimaker_abs_grey.xml.fdm_material
- ultimaker_abs_orange.xml.fdm_material
- ultimaker_abs_pearl-gold.xml.fdm_material
- ultimaker_abs_red.xml.fdm_material
- ultimaker_abs_silver-metallic.xml.fdm_material
- ultimaker_abs_white.xml.fdm_material
- ultimaker_abs_yellow.xml.fdm_material
- ultimaker_cpe_black.xml.fdm_material
- ultimaker_cpe_blue.xml.fdm_material
- ultimaker_cpe_dark-grey.xml.fdm_material
- ultimaker_cpe_green.xml.fdm_material
- ultimaker_cpe_light-grey.xml.fdm_material
- ultimaker_cpe_red.xml.fdm_material
- ultimaker_cpe_transparent.xml.fdm_material
- ultimaker_cpe_white.xml.fdm_material
- ultimaker_cpe_yellow.xml.fdm_material
- ultimaker_pla_black.xml.fdm_material
- ultimaker_pla_blue.xml.fdm_material
- ultimaker_pla_green.xml.fdm_material
- ultimaker_pla_magenta.xml.fdm_material
- ultimaker_pla_orange.xml.fdm_material
- ultimaker_pla_pearl-white.xml.fdm_material
- ultimaker_pla_red.xml.fdm_material
- ultimaker_pla_silver-metallic.xml.fdm_material
- ultimaker_pla_transparent.xml.fdm_material
- ultimaker_pla_white.xml.fdm_material
- ultimaker_pla_yellow.xml.fdm_material
These materials are auto-generated by a script, based on the generic profiles, and may contain incorrect data.
> Add an initial set of Ultimaker materials

- chromatik_pla.xml.fdm_material
- fiberlogy_hd_pla.xml.fdm_material
- filo3d_pla.xml.fdm_material
- filo3d_pla_green.xml.fdm_material
- filo3d_pla_red.xml.fdm_material
- octofiber_pla.xml.fdm_material
- polyflex_pla.xml.fdm_material
- polymax_pla.xml.fdm_material
- polyplus_pla.xml.fdm_material
- polywood_pla.xml.fdm_material
This is extracted (automatically, with a script) from the
resources/XML/xml_config.xml file installed by the Windows install
CuraByDagoma_E200_1480427910_d0965d25707767ef87c626dfbaaab4c9.zip
(dist.dagoma.fr).
Dagoma is the main distributor of these material brands.
Note: the filament_flow setting is *NOT* imported as there is no such
thing in the current Cura version in materials
Note: the color_code are not set
Note: the Cura UI is not intuitive with "Generic" types, you get menus
such as "brand → PLA → PLA", which is redundant.
Note: XML for materials, JSON for printers and INI for qualities looks
inconsistent
Note: actual printing untested
> Import Dagoma material specifications

- generic_petg.xml.fdm_material
- generic_pla.xml.fdm_material
- imade3d_petg_green.xml.fdm_material
- imade3d_petg_pink.xml.fdm_material
- imade3d_pla_green.xml.fdm_material
- imade3d_pla_pink.xml.fdm_material
- ultimaker_pc_white.xml.fdm_material
fully tested support for jellybox 3d printer. currently only adds PLA and basic PETG support.
> Add jellybox 3d printer support

- generic_abs_175.xml.fdm_material
- generic_cpe_175.xml.fdm_material
- generic_hips_175.xml.fdm_material
- generic_nylon_175.xml.fdm_material
- generic_petg_175.xml.fdm_material
- generic_pla_175.xml.fdm_material
This PR adds copies of the normal 2.85mm materials with a new GUID for 1.75mm materials. 
I have removed the special settings for Ultimaker and Cartesio printers (which don't apply because these use 2.85mm material), but left in the settings for the Jellybox.
See https://github.com/Ultimaker/Cura/pull/1685
> Add generic 1.75mm materials

- chromatik_pla.xml.fdm_material
- polyflex_pla.xml.fdm_material
- polymax_pla.xml.fdm_material
- polyplus_pla.xml.fdm_material
- polywood_pla.xml.fdm_material
This PR fixes some issues with 1.75mm materials in the repo:
* adds the missing color_code to the Chromatik PLA (which caused issues in Cura)
* groups the different Polymaker PLA variations into a single Polymaker brand
> Fix some issues with 1.75mm materials

- dsm_arnitel2045_175.xml.fdm_material
- dsm_novamid1070_175.xml.fdm_material
- generic_abs_175.xml.fdm_material
- generic_hips_175.xml.fdm_material
- generic_nylon_175.xml.fdm_material
- generic_pc_175.xml.fdm_material
- generic_petg_175.xml.fdm_material
- generic_pla_175.xml.fdm_material
- generic_pva_175.xml.fdm_material
Add new hotend IDs for cartesio.
After this has been merged we will change variant names and quality
files in Cura.
After that we will delete old hotend IDs in materials.
We do this so we will not get broken links between materials and Cura
> Changing Cartesio hotend id`s

- zyyx_pro_flex.xml.fdm_material
- zyyx_pro_pla.xml.fdm_material
Hi!
This pull adds two filaments sold by Magicfirm Europe to go with their ZYYX line of printers, it's a companion to the https://github.com/Ultimaker/Cura/pull/3584 pull in the main Cura repo.
If it's not to late I'd love if it can be merged into the upcoming 3.3 release, otherwise master will do.
> Add ZYYX materials.

- generic_pva.xml.fdm_material
- generic_pva_175.xml.fdm_material
- ultimaker_pva.xml.fdm_material
Otherwise you can never print with PVA on 3rd-party printers.
> CURA-5444 Set PVAs to be hardware compatible by default

- generic_cpe_plus.xml.fdm_material
CURA-4877 : one setting change was forgotten, making our Ultimaker material profiles deviate from the Generic ones.
( a4e54c4 )
> CPE+ fixed retraction length in generic profile

- generic_bam.xml.fdm_material
- ultimaker_bam.xml.fdm_material
Update the wording in the adhesion text (using same text as in the PVA material).
Didn't update the version number since it is only a textual change.
EM-1863
> Remove an obsolete TODO remark

- generic_abs_175.xml.fdm_material
- generic_petg_175.xml.fdm_material
- generic_pla_175.xml.fdm_material
This is an extension of this PR: https://github.com/Ultimaker/fdm_materials/pull/81
This PR depends on this Cura PR: https://github.com/Ultimaker/Cura/pull/5961, which adds the CreawsomeMod to mainline Cura.
It adds settings specific to Creality printers to these 3 materials. The difference with @trouch 's original PR is that this one has the printer definitions renamed because of the changes I made in the Cura PR.
Contributes to issue CURA-6554.
> Add CreawsomeMod settings ++

- generic_bam.xml.fdm_material
- ultimaker_bam.xml.fdm_material
Change the break speed to 25
As indicated by the Materials & Processing team.
Contributes to CURA-6661.
> Fix the case that Cura can't slice print jobs with breakaway

- imade3d_petg_175.xml.fdm_material
Previously it would put this in the quality profiles but then you can't override the temperature in the material profile.
Found during investigation of Ultimaker/Cura#6898.
> Restore 70 degree build plate for AnyCubic 4Max

- CMakeLists.txt
I think this fix the package name issue, but I don't know how you guys are used to generate the package. I tried locally and seems to work. Please test with your current workflow.
The debian package name should now be: `fdm-materials-<version>-Linux.deb`
If you run the command: `dpkg-deb -I fdm-materials-<version>-Linux.deb`
you should have an output with following line: `Package: fdm-materials`
> Change package name from fdm_materials to fdm-materials

- generic_abs.xml.fdm_material
- generic_cpe_plus.xml.fdm_material
- generic_pc.xml.fdm_material
- generic_pp.xml.fdm_material
- ultimaker_abs_black.xml.fdm_material
- ultimaker_abs_blue.xml.fdm_material
- ultimaker_abs_grey.xml.fdm_material
- ultimaker_abs_orange.xml.fdm_material
- ultimaker_abs_pearl-gold.xml.fdm_material
- ultimaker_abs_red.xml.fdm_material
- ultimaker_abs_silver-metallic.xml.fdm_material
- ultimaker_abs_white.xml.fdm_material
- ultimaker_abs_yellow.xml.fdm_material
- ultimaker_cpe_plus_black.xml.fdm_material
- ultimaker_cpe_plus_transparent.xml.fdm_material
- ultimaker_cpe_plus_white.xml.fdm_material
- ultimaker_pc_black.xml.fdm_material
- ultimaker_pc_transparent.xml.fdm_material
- ultimaker_pc_white.xml.fdm_material
- ultimaker_pp_transparent.xml.fdm_material
Change unit of shrinkage compensation setting.
Since the setting is now visible in the user interface, we've decided on a bit more of a logical unit for it. It's now based around 100%. If it's 100%, the material is assumed to not shrink or expand at all, when cooling.
Contributes to issue CURA-7118.
Please consolidate discussions about the architecture of this setting to the CuraEngine PR: https://github.com/Ultimaker/CuraEngine/pull/1316
> Shrinkage compensation

- generic_abs.xml.fdm_material
- generic_cpe_plus.xml.fdm_material
- generic_pc.xml.fdm_material
- generic_pp.xml.fdm_material
- ultimaker_abs_black.xml.fdm_material
- ultimaker_abs_blue.xml.fdm_material
- ultimaker_abs_green.xml.fdm_material
- ultimaker_abs_grey.xml.fdm_material
- ultimaker_abs_orange.xml.fdm_material
- ultimaker_abs_pearl-gold.xml.fdm_material
- ultimaker_abs_red.xml.fdm_material
- ultimaker_abs_silver-metallic.xml.fdm_material
- ultimaker_abs_white.xml.fdm_material
- ultimaker_abs_yellow.xml.fdm_material
- ultimaker_cpe_plus_black.xml.fdm_material
- ultimaker_cpe_plus_transparent.xml.fdm_material
- ultimaker_cpe_plus_white.xml.fdm_material
- ultimaker_pc_black.xml.fdm_material
- ultimaker_pc_transparent.xml.fdm_material
- ultimaker_pc_white.xml.fdm_material
- ultimaker_pp_transparent.xml.fdm_material
It turns out that the Ultimaker firmware was not actually using this setting, but it was validating it to be between 0 and 100%, basically validating that a material shouldn't shrink to less than 50% of its original size. When we changed the unit of this setting, this caused their firmware to no longer read these materials.
This change makes this use the Cura namespace and the Cura setting name, so the firmware doesn't recognise the setting any more.
Contributes to issue CURA-7724.
> Change shrinkage percentage overrides to Cura-specific settings

- generic_cpe.xml.fdm_material
- ultimaker_cpe_black.xml.fdm_material
- ultimaker_cpe_blue.xml.fdm_material
- ultimaker_cpe_dark-grey.xml.fdm_material
- ultimaker_cpe_green.xml.fdm_material
- ultimaker_cpe_light-grey.xml.fdm_material
- ultimaker_cpe_red.xml.fdm_material
- ultimaker_cpe_transparent.xml.fdm_material
- ultimaker_cpe_white.xml.fdm_material
- ultimaker_cpe_yellow.xml.fdm_material
Update build plate temperature CPE to 85C for all printers to improve build plate adhesion.
Approved by Quality.
> Update build plate temperature CPE

- generic_petg.xml.fdm_material
- generic_petg_175.xml.fdm_material
The most commonly sold PETG type have density 1270 kg/m³
The pure PET has density 1.38, but PETG that often used in 3d printing has lower densities (1.24-1.27).
It make more sense to have in Generic PETG profile setting that applies to most of sold materials.
Sources:
- https://en.wikipedia.org/wiki/3D_printing_filament#Materials
- https://www.simplify3d.com/support/materials-guide/properties-table/
- https://shop.prusa3d.com/fotky/PETG_TechSheet_ENG.pdf
- https://github.com/prusa3d/PrusaSlicer/blob/master/resources/profiles/Creality.ini#L246
- https://github.com/prusa3d/PrusaSlicer/blob/master/resources/profiles/PrusaResearch.ini#L1880
> Set generic PETG density to 1.27

- generic_abs.xml.fdm_material
- generic_bam.xml.fdm_material
- generic_cpe.xml.fdm_material
- generic_cpe_plus.xml.fdm_material
- generic_nylon.xml.fdm_material
- generic_pc.xml.fdm_material
- generic_petg.xml.fdm_material
- generic_pla.xml.fdm_material
- generic_pp.xml.fdm_material
- generic_pva.xml.fdm_material
- generic_tough_pla.xml.fdm_material
- generic_tpu.xml.fdm_material
Please note that only generic profiles that have an equivalent ultimaker profile are updated. Other generic profiles still have the old deprime.
> MISP-1466_Update generic profiles for new deprime

- ultimaker_pla_black.xml.fdm_material
- ultimaker_pla_blue.xml.fdm_material
- ultimaker_pla_green.xml.fdm_material
- ultimaker_pla_magenta.xml.fdm_material
- ultimaker_pla_orange.xml.fdm_material
- ultimaker_pla_pearl-white.xml.fdm_material
- ultimaker_pla_red.xml.fdm_material
- ultimaker_pla_silver-metallic.xml.fdm_material
- ultimaker_pla_transparent.xml.fdm_material
- ultimaker_pla_white.xml.fdm_material
- ultimaker_pla_yellow.xml.fdm_material
Copied CC 0.4 and CC 0.4 settings from GENERIC PLA to Ultimaker PLA materials
We are not sure if the PR #172 is ok only for GENERIC materials. where PLA we also have Ultimaker materials.
https://github.com/Ultimaker/fdm_materials/pull/172
> made CC 0.4 and CC 0.4 compatible with Ultimaker PLA

- ultimaker_pc_black.xml.fdm_material
- ultimaker_pc_transparent.xml.fdm_material
- ultimaker_pc_white.xml.fdm_material
- ultimaker_pva.xml.fdm_material
These lines were (accidentally) copied over from the generic materials, but lead to issues in our Material Marketplace.
> Removes Cartesio compatibility from Ultimaker materials

- generic_abs_175.xml.fdm_material
- generic_petg_175.xml.fdm_material
- generic_pla_175.xml.fdm_material
Removed machine identifier "Tronxy_X5SA_Pro" as it is no longer an active profile in Cura (was removed in the 2020 update PR)
Removed retraction speeds and distance values in order to move them under each individual printer, as bowden lengths and feed styles vary. Also to avoid conflicts between the FDM profiles and printer profiles.
An update of Tronxy machine profiles is currently being worked on and these changes should be made concurrently.
> Tronxy Update 2022

- generic_abs.xml.fdm_material
- ultimaker_abs_black.xml.fdm_material
- ultimaker_abs_blue.xml.fdm_material
- ultimaker_abs_green.xml.fdm_material
- ultimaker_abs_grey.xml.fdm_material
- ultimaker_abs_orange.xml.fdm_material
- ultimaker_abs_pearl-gold.xml.fdm_material
- ultimaker_abs_red.xml.fdm_material
- ultimaker_abs_silver-metallic.xml.fdm_material
- ultimaker_abs_white.xml.fdm_material
- ultimaker_abs_yellow.xml.fdm_material
ABS is stringy because of the short retract (5mm). With the updated retract speeds (PP-96) we can safely increase the retract length to the default of 6.5mm. PP-101
> increase retract distance of ABS

- generic_cpe.xml.fdm_material
- generic_cpe_plus.xml.fdm_material
- ultimaker_cpe_black.xml.fdm_material
- ultimaker_cpe_blue.xml.fdm_material
- ultimaker_cpe_dark-grey.xml.fdm_material
- ultimaker_cpe_green.xml.fdm_material
- ultimaker_cpe_light-grey.xml.fdm_material
- ultimaker_cpe_plus_black.xml.fdm_material
- ultimaker_cpe_plus_transparent.xml.fdm_material
- ultimaker_cpe_plus_white.xml.fdm_material
- ultimaker_cpe_red.xml.fdm_material
- ultimaker_cpe_transparent.xml.fdm_material
- ultimaker_cpe_white.xml.fdm_material
- ultimaker_cpe_yellow.xml.fdm_material
All ultimaker profiles get a default max combing distance of 15mm to avoid oozing in the infill. Profile/material specific settings are removed. PP-69
> PP-69-default-max-comb-distance

- scripts/fdmmaterial.xsd
- ultimaker_abs.xml.fdm_material
- ultimaker_cpe.xml.fdm_material
- ultimaker_cpe_plus.xml.fdm_material
- ultimaker_nylon.xml.fdm_material
- ultimaker_pc.xml.fdm_material
- ultimaker_petcf.xml.fdm_material
- ultimaker_petg.xml.fdm_material
- ultimaker_pla.xml.fdm_material
- ultimaker_tough_pla.xml.fdm_material
- ultimaker_tpu.xml.fdm_material
Add Generic (Any color) material profiles. 
First merge: https://github.com/Ultimaker/fdm_materials/pull/262 to allow for the new <abstract_color> tag
PP-245
> Add Generic (Any color) material profiles

- emotiontech_abs.xml.fdm_material
- emotiontech_absx.xml.fdm_material
- emotiontech_acetate.xml.fdm_material
- emotiontech_asax.xml.fdm_material
- emotiontech_bvoh.xml.fdm_material
- emotiontech_copa.xml.fdm_material
- emotiontech_hips.xml.fdm_material
- emotiontech_nylon_1030.xml.fdm_material
- emotiontech_nylon_1030cf.xml.fdm_material
- emotiontech_nylon_1070.xml.fdm_material
- emotiontech_pa6cf.xml.fdm_material
- emotiontech_pa6gf.xml.fdm_material
- emotiontech_pc.xml.fdm_material
- emotiontech_pekk.xml.fdm_material
- emotiontech_pla.xml.fdm_material
- emotiontech_pla_hr_870.xml.fdm_material
- emotiontech_pva-m.xml.fdm_material
- emotiontech_pva-s.xml.fdm_material
- emotiontech_tpu98a.xml.fdm_material
- nylon_1030, nylon_1030CF, nylon_1070 are now "deprecated" (see label in files)
- pa6CF and pa6GF are added to eMotionTech catalogue
- Strateo3D machine is renamed "DUAL600" because Strateo3D is a brand of several machines (DUAL600 and IDEX420)
- Strateo IDEX420 mchine is added to material files
> eMotionTech - Updating material files

- conanfile.py
- ultimaker_abscf_175.xml.fdm_material
- ultimaker_absr_175.xml.fdm_material
- ultimaker_rapidrinse_175.xml.fdm_material
Turn on prime tower even when support is disabled
> CURA-11291 Turn on prime tower even when support is disabled

- ultimaker_abscf_175.xml.fdm_material
- ultimaker_absr_175.xml.fdm_material
- ultimaker_rapidrinse_175.xml.fdm_material
- Add prime tower when raft uses Method support materials (even when self support is enabled).
- In principle the prime tower should also be on when two model materials are used. However, Method machine do not support this, so this use case does not have to be covered.
PP-401
> Add prime tower when raft contains support material

- generic_abs_175.xml.fdm_material
- generic_asa_175.xml.fdm_material
- generic_nylon_175.xml.fdm_material
- generic_pc_175.xml.fdm_material
- generic_petg_175.xml.fdm_material
- generic_pla_175.xml.fdm_material
- generic_pva_175.xml.fdm_material
- scripts/fdmmaterial.xsd
- ultimaker_abscf_175.xml.fdm_material
- ultimaker_absr_175.xml.fdm_material
- ultimaker_rapidrinse_175.xml.fdm_material
We had a lot of Look up Tables scattered around in the cura repository. This can be solved by adding a `bot_id` entry to metadata of the various makerbot extruders/materials/definitions
> Clean up bot LUT

- .github/workflows/conan-package.yml
- .github/workflows/process-pull-request.yml
- conandata.yml
- conanfile.py
Ported a lot of workflow to use the reusable workflows in the new [Cura-workflows](https://github.com/Ultimaker/Cura-workflows) repository. See PR: https://github.com/Ultimaker/cura-workflows/pull/1 
The biggest impact on this repository is that the version of the conan package is now determined by the `version` key in `conandata.yml` and no longer determined based on the git tag. During a push the Conan user, channel is determined based Github runner context, see the `conan-recipe-versions.yml` in the Cura-workflows and the semver build metadata is added from the sha of the reference name (git hash).
**Test Configuration**:
* Operating System: Linux, Windows, Mac
> CURA-10831

- ultimaker_asa_175.xml.fdm_material
- ultimaker_nylon12-cf_175.xml.fdm_material
The Method X and Method XL sections were missing in the profiles leading to wrong settings.
> Fix ASA and PA12-CF material profiles

- CMakeLists.txt
This is now set in the conan_toolchain.cmake itself and no longer needs to be specified by us generally.
This allows older cmake versions to still create a Debian package
> remove cmake policy

- ultimaker_metallic_pla_175.xml.fdm_material
Previously we used the PLA profile to print Metallic PLA.
There were drastic differences in surface quality (matte vs shiny).
Also, nozzle failures should be reduced with settings
adjustments made specifically for this material.
New material and quality files were added to address these issues.
PP-552
> Add metallic PLA material for Sketch printers

- ultimaker_pla_175.xml.fdm_material
Curator has the following assumptions when creating the matcher for  a material.
If in the machine block of an fdm_material there is **ANY** hotend defined then the other hotends for that material are incompatible.  See UltiMaker PLA forn the S-lines they don't define CC and DD cores therefore and Cura marks them as incompatible.
If there are **NO** hotend defined in any hotend for that machine is compatible.
And a dev can set the the hardware compatibility explicit to yes/no
This seemed to work for everything, but apparently Cura still does some other Voodoo Magic.
Adding support in the resources itself is easier than changing the business logic in Curator for this:
- https://github.com/Ultimaker/Curator/blob/c3c0c5a62b4579dd1d69c63d24124a1fa944df5c/include/curator/settings/data/material. …
> NP-862 replicator support cura cloud
