Ultimaker/fdm_materials

innofill_innoflex60_175.xml.fdm_material
verbatim_bvoh_175.xml.fdm_material

Add Innofill Innoflex60 and Verbatim BVOH materials 1.75 mm filament

Add Innofill Innoflex60 and Verbatim BVOH

---

Vertex_Delta_ABS.xml.fdm_material
Vertex_Delta_PET.xml.fdm_material
Vertex_Delta_PLA.xml.fdm_material
Vertex_Delta_TPU.xml.fdm_material

Hi
We've added our PLA,ABS,PET and TPU filaments

Add Velleman Profiles

---

fabtotum_nylon.xml.fdm_material
fabtotum_tpu.xml.fdm_material

TPU Fabtotum's profiles

---

generic_pla.xml.fdm_material
ultimaker_pla_black.xml.fdm_material
ultimaker_pla_blue.xml.fdm_material
ultimaker_pla_green.xml.fdm_material
ultimaker_pla_magenta.xml.fdm_material
ultimaker_pla_orange.xml.fdm_material
ultimaker_pla_pearl-white.xml.fdm_material
ultimaker_pla_red.xml.fdm_material
ultimaker_pla_silver-metallic.xml.fdm_material

3.3optimization

---

generic_abs.xml.fdm_material
generic_cpe_plus.xml.fdm_material
generic_pc.xml.fdm_material
generic_pp.xml.fdm_material

For models that are bigger than 15x15x10cm (any direction) and printed in
- ABS
- PC
- PP
- CPE+
we would like to give some tips to the user.

CURA-4557 model checker

---

dsm_arnitel2045_175.xml.fdm_material
dsm_novamid1070_175.xml.fdm_material
generic_abs_175.xml.fdm_material
generic_hips_175.xml.fdm_material
generic_nylon_175.xml.fdm_material
generic_pc.xml.fdm_material
generic_pc_175.xml.fdm_material
generic_petg_175.xml.fdm_material
generic_pla_175.xml.fdm_material
generic_pva.xml.fdm_material
generic_pva_175.xml.fdm_material
ultimaker_pc_black.xml.fdm_material
ultimaker_pc_transparent.xml.fdm_material
ultimaker_pc_white.xml.fdm_material
ultimaker_pva.xml.fdm_material

CURA-5578 Remove Cartesio old variants

---

scripts/check_material_profiles.py
scripts/check_material_profiles_new_with_lxml.py
scripts/fdmmaterial.xsd
ultimaker_pva.xml.fdm_material

As the name suggests. I've added an XSD that validates if a material profile is correct.

Improve material validation script

---

ultimaker_tough_pla_black.xml.fdm_material
ultimaker_tough_pla_green.xml.fdm_material
ultimaker_tough_pla_red.xml.fdm_material
ultimaker_tough_pla_white.xml.fdm_material

As per our code style and to be consistent.
Waste of time to have to create a branch, push the branch, create a PR, type a message, then review the PR, checkout the branch and merge the branch. But oh well here we go.

Replace tabs with spaces

---

generic_cffcpe.xml.fdm_material
generic_cffpa.xml.fdm_material
generic_gffcpe.xml.fdm_material
generic_gffpa.xml.fdm_material

Remove UM3 and UM3Ext for CFF and GFF materials

---

generic_abs_175.xml.fdm_material
generic_pla_175.xml.fdm_material

Adding temps for HMS434
updating temps for Cartesio

Adding temps for HMS434

---

scripts/check_material_profiles.py
scripts/check_material_profiles_new_with_lxml.py

We want to clean up the test output if the tests succeeded so it is easier to find the tests that failed.

Remove prints if tests succeeded

---

tizyx_abs.xml.fdm_material
tizyx_flex.xml.fdm_material
tizyx_petg.xml.fdm_material
tizyx_pla.xml.fdm_material
tizyx_pla_bois.xml.fdm_material
tizyx_pva.xml.fdm_material

Hello,
We have added pva, flex and petg materials and updated pla, pla bois and abs
Thanks

TiZYX update

---

Vertex_Delta_PLA_Glitter.xml.fdm_material
Vertex_Delta_PLA_Mat.xml.fdm_material
Vertex_Delta_PLA_Satin.xml.fdm_material
Vertex_Delta_PLA_Wood.xml.fdm_material

Updated PLA settings with values from manufacturer.
New materials
PLA matt
PLA Satin
PLA Glitter
PLA wood

Update PLA and add new materials

---

emotiontech_abs.xml.fdm_material
emotiontech_petg.xml.fdm_material
emotiontech_pla.xml.fdm_material
emotiontech_pva-m.xml.fdm_material
emotiontech_pva-oks.xml.fdm_material
emotiontech_pva-s.xml.fdm_material
emotiontech_tpu98a.xml.fdm_material

Hello,
Adding some materials for eMotionTech's printers (specially Strateo3D)
Thanks

First_eMotionTech_Material_Pull

---

generic_cffcpe.xml.fdm_material
generic_cffpa.xml.fdm_material
generic_gffcpe.xml.fdm_material
generic_gffpa.xml.fdm_material
generic_pva.xml.fdm_material
ultimaker_pva.xml.fdm_material

Updated build volume temperature for
PVA, CFFPA, CFFCPE, GFFPA, GFFCPE

Update build volume temperature

---

generic_cffcpe.xml.fdm_material
generic_cpe.xml.fdm_material
generic_cpe_175.xml.fdm_material
ultimaker_cpe_black.xml.fdm_material
ultimaker_cpe_blue.xml.fdm_material
ultimaker_cpe_dark-grey.xml.fdm_material
ultimaker_cpe_green.xml.fdm_material
ultimaker_cpe_light-grey.xml.fdm_material
ultimaker_cpe_red.xml.fdm_material
ultimaker_cpe_transparent.xml.fdm_material
ultimaker_cpe_white.xml.fdm_material
ultimaker_cpe_yellow.xml.fdm_material

CPE build volume temperature increased to increase reliability

Changed build volume temperature for CPE

---

generic_cffcpe.xml.fdm_material
generic_cffpa.xml.fdm_material
generic_gffcpe.xml.fdm_material
generic_gffpa.xml.fdm_material
generic_hips.xml.fdm_material
generic_nylon.xml.fdm_material
generic_pp.xml.fdm_material
generic_pva.xml.fdm_material
ultimaker_nylon_black.xml.fdm_material
ultimaker_nylon_transparent.xml.fdm_material
ultimaker_pp_transparent.xml.fdm_material
ultimaker_pva.xml.fdm_material

as was intended acording to tom Heijmans
Signed-off-by: Robin den Hertog <r.denhertog@ultimaker.com>

ST-2861: set all break speeds to 25 mm/s

---

CMakeLists.txt

https://github.com/Ultimaker/fdm_materials/commit/73669d9a690e3f92b5e7651d3d2dab6b633aec1d#commitcomment-36418232

Attempt to fix Cura build error

---

scripts/check_material_profiles_new_with_lxml.py

Noticed this issue in PR https://github.com/Ultimaker/fdm_materials/pull/102/files

Handle XMLSyntaxError in check script

---

scripts/fdmmaterial.xsd

Input validation for brand, material and color. 2 <= length <= 100 characters.

CS-676 XSD template input validation for brand, material and color

---

generic_pva.xml.fdm_material
generic_tough_pla.xml.fdm_material
ultimaker_pva.xml.fdm_material
ultimaker_tough_pla_black.xml.fdm_material
ultimaker_tough_pla_green.xml.fdm_material
ultimaker_tough_pla_red.xml.fdm_material
ultimaker_tough_pla_white.xml.fdm_material

These commits should improve PVA and Tough PLA reliability by reducing grinding (PVA) and force needed for deprime (Tough PLA)

Material station reliability improvements

---

generic_abs_175.xml.fdm_material
generic_petg_175.xml.fdm_material
generic_pla_175.xml.fdm_material

#129 was accidentally deleted from my repositories
Re-opening PR

Material updates to include Tronxy machines

---

generic_cpe.xml.fdm_material
generic_cpe_plus.xml.fdm_material
ultimaker_cpe_black.xml.fdm_material
ultimaker_cpe_blue.xml.fdm_material
ultimaker_cpe_dark-grey.xml.fdm_material
ultimaker_cpe_green.xml.fdm_material
ultimaker_cpe_light-grey.xml.fdm_material
ultimaker_cpe_plus_black.xml.fdm_material
ultimaker_cpe_plus_transparent.xml.fdm_material
ultimaker_cpe_plus_white.xml.fdm_material
ultimaker_cpe_red.xml.fdm_material
ultimaker_cpe_transparent.xml.fdm_material
ultimaker_cpe_white.xml.fdm_material
ultimaker_cpe_yellow.xml.fdm_material

For UM3 printer and CPE & CPE+ materials
Max comb with no retract = 40 
combing mode = All

Um3 max comb without retract for cpe and cpe+

---

generic_pla_175.xml.fdm_material

This is the tweaked materials file for the PR below. It allows a specific temp to be set for the B1 machine when using PLA.
https://github.com/Ultimaker/Cura/pull/8276

Added machine specific PLA material profile for BIQU B1

---

generic_abs.xml.fdm_material
generic_cpe_plus.xml.fdm_material
generic_pc.xml.fdm_material
generic_pp.xml.fdm_material
ultimaker_abs_black.xml.fdm_material
ultimaker_abs_blue.xml.fdm_material
ultimaker_abs_green.xml.fdm_material
ultimaker_abs_grey.xml.fdm_material
ultimaker_abs_orange.xml.fdm_material
ultimaker_abs_pearl-gold.xml.fdm_material
ultimaker_abs_red.xml.fdm_material
ultimaker_abs_silver-metallic.xml.fdm_material
ultimaker_abs_white.xml.fdm_material
ultimaker_abs_yellow.xml.fdm_material
ultimaker_cpe_plus_black.xml.fdm_material
ultimaker_cpe_plus_transparent.xml.fdm_material
ultimaker_cpe_plus_white.xml.fdm_material
ultimaker_pc_black.xml.fdm_material
ultimaker_pc_transparent.xml.fdm_material
ultimaker_pc_white.xml.fdm_material
ultimaker_pp_transparent.xml.fdm_material

Set material shrinkage percentage to 100

---

generic_tpu.xml.fdm_material
ultimaker_tpu_black.xml.fdm_material
ultimaker_tpu_blue.xml.fdm_material
ultimaker_tpu_red.xml.fdm_material
ultimaker_tpu_white.xml.fdm_material

Set build plate temp to 0C for UM2+Connect

Update build plate temp for TPU

---

layer_one_black_pla.xml.fdm_material
layer_one_dark_gray_pla.xml.fdm_material
layer_one_white_pla.xml.fdm_material

Adds files for Layer Ones PLA materials in 3 colors.

feat: Adds 3 PLA materials from Layer One

---

scripts/fdmmaterial.xsd
ultimaker_pla_black.xml.fdm_material
ultimaker_pla_blue.xml.fdm_material
ultimaker_pla_green.xml.fdm_material
ultimaker_pla_magenta.xml.fdm_material
ultimaker_pla_orange.xml.fdm_material
ultimaker_pla_pearl-white.xml.fdm_material
ultimaker_pla_red.xml.fdm_material
ultimaker_pla_silver-metallic.xml.fdm_material
ultimaker_pla_transparent.xml.fdm_material
ultimaker_pla_white.xml.fdm_material
ultimaker_pla_yellow.xml.fdm_material
ultimaker_tough_pla_black.xml.fdm_material
ultimaker_tough_pla_green.xml.fdm_material
ultimaker_tough_pla_red.xml.fdm_material
ultimaker_tough_pla_white.xml.fdm_material
ultimaker_tpu_black.xml.fdm_material
ultimaker_tpu_blue.xml.fdm_material
ultimaker_tpu_red.xml.fdm_material
ultimaker_tpu_white.xml.fdm_material

I never did a PR before on fdm_materials. So please let me know if I did something wrong.

Misp 1335 ultimaker tpu pla tough pla

---

ultimaker_abs_black.xml.fdm_material
ultimaker_abs_blue.xml.fdm_material
ultimaker_abs_green.xml.fdm_material
ultimaker_abs_grey.xml.fdm_material
ultimaker_abs_orange.xml.fdm_material
ultimaker_abs_pearl-gold.xml.fdm_material
ultimaker_abs_red.xml.fdm_material
ultimaker_abs_silver-metallic.xml.fdm_material
ultimaker_abs_white.xml.fdm_material
ultimaker_abs_yellow.xml.fdm_material
ultimaker_bam.xml.fdm_material
ultimaker_cpe_black.xml.fdm_material
ultimaker_cpe_blue.xml.fdm_material
ultimaker_cpe_dark-grey.xml.fdm_material
ultimaker_cpe_green.xml.fdm_material
ultimaker_cpe_light-grey.xml.fdm_material
ultimaker_cpe_plus_black.xml.fdm_material
ultimaker_cpe_plus_transparent.xml.fdm_material
ultimaker_cpe_plus_white.xml.fdm_material
ultimaker_cpe_red.xml.fdm_material
ultimaker_cpe_transparent.xml.fdm_material
ultimaker_cpe_white.xml.fdm_material
ultimaker_cpe_yellow.xml.fdm_material
ultimaker_pc_black.xml.fdm_material
ultimaker_pc_transparent.xml.fdm_material
ultimaker_pc_white.xml.fdm_material

I already increased the version number. The last batch of materials will follow soon.

Misp 1335 ultimaker cpe+ abs bam pc cpe

---

ultimaker_nylon_black.xml.fdm_material
ultimaker_nylon_transparent.xml.fdm_material
ultimaker_pp_transparent.xml.fdm_material
ultimaker_pva.xml.fdm_material

And here we go: the last batch of upgrade deprime profiles.

Misp 1335 ultimaker nylon pp pva

---

generic_petg.xml.fdm_material
ultimaker_petg_black.xml.fdm_material
ultimaker_petg_blue.xml.fdm_material
ultimaker_petg_blue_translucent.xml.fdm_material
ultimaker_petg_green.xml.fdm_material
ultimaker_petg_green_translucent.xml.fdm_material
ultimaker_petg_grey.xml.fdm_material
ultimaker_petg_orange.xml.fdm_material
ultimaker_petg_red.xml.fdm_material
ultimaker_petg_red_translucent.xml.fdm_material
ultimaker_petg_silver.xml.fdm_material
ultimaker_petg_transparent.xml.fdm_material
ultimaker_petg_white.xml.fdm_material
ultimaker_petg_yellow.xml.fdm_material
ultimaker_petg_yellow_fluorescent.xml.fdm_material

PETG for UM3

---

generic_cffcpe.xml.fdm_material
generic_cffpa.xml.fdm_material
generic_gffcpe.xml.fdm_material
generic_gffpa.xml.fdm_material
generic_pla.xml.fdm_material

Made changes in the CC core materials to add CC0.4 print core materials settings.
Related to https://github.com/Ultimaker/Cura/pull/9937.

CC0.4_Print_Profile_materials

---

generic_cffcpe.xml.fdm_material
generic_cffpa.xml.fdm_material
generic_gffcpe.xml.fdm_material
generic_gffpa.xml.fdm_material
generic_pla.xml.fdm_material

Required after changes in https://github.com/Ultimaker/fdm_materials/pull/172.

Bump up file version

---

Extrudr_GreenTECPro_Anthracite_175.xml.fdm_material
xyzprinting_abs.xml.fdm_material
xyzprinting_antibact_pla.xml.fdm_material
xyzprinting_carbon_fiber.xml.fdm_material
xyzprinting_colorinkjet_pla.xml.fdm_material
xyzprinting_flexible.xml.fdm_material
xyzprinting_metallic_pla.xml.fdm_material
xyzprinting_nylon.xml.fdm_material
xyzprinting_petg.xml.fdm_material
xyzprinting_pla.xml.fdm_material
xyzprinting_tough_pla.xml.fdm_material
xyzprinting_tpu.xml.fdm_material

Add XYZprinting materials

---

generic_bam.xml.fdm_material
generic_pva.xml.fdm_material
ultimaker_bam.xml.fdm_material
ultimaker_pva.xml.fdm_material

PP-166 Create print profiles for the new DD core
Updated support material profiles to disable their compatibility with the new DD core
Related to PP-166
Needs to be pulled together with the following pull request in the Cura repository: https://github.com/Ultimaker/Cura/pull/12465

PP-166 Create print profiles for the new DD core

---

ultimaker_tough_pla_blue.xml.fdm_material
ultimaker_tough_pla_gray.xml.fdm_material
ultimaker_tough_pla_yellow.xml.fdm_material

Material profiles for three new Tough PLA colours: Gray, Yellow, blue. To be added in Cura 5.1 beta and S-line 7.0.4 and UM2+Connect FW releases.
Related to PP-177

PP-177-Tough PLA new colours - material profiles

---

.github/workflows/conan-package.yml

Use python 3.10.x

---

.github/workflows/conan-package.yml

Also run on master

---

.github/workflows/conan-package.yml

Also run when runner requirements change

---

ultimaker_abs_silver-metallic.xml.fdm_material

PP-274-rename-ABS-silver

---

eSUN_PLA_PRO_Black.xml.fdm_material
eSUN_PLA_PRO_Grey.xml.fdm_material
eSUN_PLA_PRO_Purple.xml.fdm_material
eSUN_PLA_PRO_White.xml.fdm_material

The material would show up as unsupported, updated the material/label combination so it shows up correctly.
Should resolve reports like this: https://github.com/Ultimaker/Cura/issues/14644
I also checked if there are other "unsupported" materials but that doesn't seem to be the case.

Update esun PLA+

---

conanfile.py

Use new package structure

---

conanfile.py

add missing imports

---

generic_petcf.xml.fdm_material
ultimaker_petcf_black.xml.fdm_material
ultimaker_petcf_blue.xml.fdm_material
ultimaker_petcf_gray.xml.fdm_material

For PET-CF materials
Relates to: PP-340

Added new profiles

---

generic_tpu.xml.fdm_material
ultimaker_tpu_black.xml.fdm_material
ultimaker_tpu_blue.xml.fdm_material
ultimaker_tpu_red.xml.fdm_material
ultimaker_tpu_white.xml.fdm_material

PP-359_Add_break_position_to_TPU_profiles

---

ultimaker_abs.xml.fdm_material
ultimaker_cpe.xml.fdm_material
ultimaker_cpe_plus.xml.fdm_material
ultimaker_nylon.xml.fdm_material
ultimaker_pc.xml.fdm_material
ultimaker_petg.xml.fdm_material
ultimaker_tough_pla.xml.fdm_material
ultimaker_tpu.xml.fdm_material

Apply PP-350 to the Any Color profiles from PP-245.
CURA-11060

Apply PP-350 to Any Color profiles

---

generic_pva_175.xml.fdm_material
ultimaker_abscf_175.xml.fdm_material
ultimaker_absr_175.xml.fdm_material
ultimaker_rapidrinse_175.xml.fdm_material

- Ultimaker Method X & XL Material profiles

Method material profiles

---

ultimaker_abscf_175.xml.fdm_material
ultimaker_absr_175.xml.fdm_material
ultimaker_rapidrinse_175.xml.fdm_material

CURA-11262 Renamed Makerbot to UltiMaker in material profiles for the Methods

---

ultimaker_rapidrinse_175.xml.fdm_material

@pkuiper-ultimaker please don't forget that bugfixes like these should be against the release-branch (if available in the repo) ;-)
CURA-11291

Turn on prime tower even if the support is disabled

---

ultimaker_abscf_175.xml.fdm_material
ultimaker_absr_175.xml.fdm_material
ultimaker_rapidrinse_175.xml.fdm_material

PP-399 
ABS-CF
"xScale": 1.0016,
"yScale": 1.0016,
"zScale": 1.0068
ABSR
"xScale": 1.0057,
"yScale": 1.0057,
"zScale": 1.0059

Shrinkage compensation method materials

---

generic_asa_175.xml.fdm_material
ultimaker_asa_175.xml.fdm_material
ultimaker_nylon12-cf_175.xml.fdm_material
ultimaker_sr30_175.xml.fdm_material

Added new materials for the Method X and Method XL: ASA, Nylon12-CF and SR-30
PP-393

PP-393 ASA, Nylon12-CF and SR-30 print profile

---

conandata.yml

version change to next release

version change to next release

---

ultimaker_pla_175.xml.fdm_material
ultimaker_tough_pla_175.xml.fdm_material

Ultimaker 1.75mm PLA and T-PLA for the Sketch and Method

---

generic_pva.xml.fdm_material
ultimaker_pva.xml.fdm_material

Prevent false positives ER314 trips
PP-494

Increase flow sensor margin from 20% to 50% 

---

conandata.yml

bump to 5.9.0-alpha.0

---

ultimaker_pla_175.xml.fdm_material
ultimaker_tough_pla_175.xml.fdm_material

PP-520 Sketch / Sketch Large Tough PLA & PLA

---

ultimaker_pc-abs-fr_175.xml.fdm_material
ultimaker_pc-abs_175.xml.fdm_material

Add material profiles for PC-ABS and PC-ABS-FR.
These materials are supported for Method X and
Method XL (extruders 1XA, 1C & Labs).
PP-550

PC-ABS & PC-ABS-FR 175 Profiles

---

ultimaker_pla_175.xml.fdm_material
ultimaker_tough_pla_175.xml.fdm_material

Update PLA & TPLA 175 with Rep+ values

---

generic_cffpps.xml.fdm_material
generic_pla.xml.fdm_material
generic_pva.xml.fdm_material
ultimaker_pla.xml.fdm_material
ultimaker_pla_black.xml.fdm_material
ultimaker_pla_blue.xml.fdm_material
ultimaker_pla_green.xml.fdm_material
ultimaker_pla_magenta.xml.fdm_material
ultimaker_pla_orange.xml.fdm_material
ultimaker_pla_pearl-white.xml.fdm_material
ultimaker_pla_red.xml.fdm_material
ultimaker_pla_silver-metallic.xml.fdm_material
ultimaker_pla_transparent.xml.fdm_material
ultimaker_pla_white.xml.fdm_material
ultimaker_pla_yellow.xml.fdm_material
ultimaker_ppscf_metallic-anthracite.xml.fdm_material
ultimaker_pva.xml.fdm_material

- Mark PPS-CF as not compatible with S-line
- Mark PVA as not compatible with non-BB cores for S8
- Mark PLA as not compatible with CC+ cores

[PP-594] Update compatibilities

---

generic_petcf.xml.fdm_material
ultimaker_petcf.xml.fdm_material
ultimaker_petcf_black.xml.fdm_material
ultimaker_petcf_blue.xml.fdm_material
ultimaker_petcf_gray.xml.fdm_material

Reduce PET-CF retract distance from 10mm to 8mm.

---

generic_nylon-cf-slide.xml.fdm_material
ultimaker_nylon-cf-slide.xml.fdm_material

PP-599 shorter retract distance

---

generic_cpe_plus.xml.fdm_material
generic_pc.xml.fdm_material
ultimaker_cpe_plus.xml.fdm_material
ultimaker_cpe_plus_black.xml.fdm_material
ultimaker_cpe_plus_transparent.xml.fdm_material
ultimaker_cpe_plus_white.xml.fdm_material
ultimaker_pc.xml.fdm_material
ultimaker_pc_black.xml.fdm_material
ultimaker_pc_transparent.xml.fdm_material
ultimaker_pc_white.xml.fdm_material

PP-625 Improvements to S8 profiles

---

ultimaker_rapidrinse_175.xml.fdm_material

Less chance on jamming.
PP-622

Reliability improvements to the RapidRinse raft settings

---

generic_petcf.xml.fdm_material
ultimaker_petcf.xml.fdm_material
ultimaker_petcf_black.xml.fdm_material
ultimaker_petcf_blue.xml.fdm_material
ultimaker_petcf_gray.xml.fdm_material

Reduced retraction length to 4mm.
PP-659

Profile improvements PET-CF material
